services:
    welp_batch.operation_manager:
        class: Welp\BatchBundle\Manager\OperationManager
        arguments : ['@%welp_batch.entity_manager%', '@service_container', %welp_batch.batch_entity.batch%]
    welp_batch.batch_manager:
        class: Welp\BatchBundle\Manager\BatchManager
        arguments : ['@%welp_batch.entity_manager%', '@service_container', %welp_batch.batch_entity.operation%]
    welp_batch.batch_provider:
        class: Welp\BatchBundle\Manager\BatchManager
        arguments : ['@%welp_batch.entity_manager%', '@service_container', @welp_batch.batch_manager,@welp_batch.operation_manager ]
