services:
    welp_ical.factory:
        class: Welp\BatchBundle\Factory\Factory
        arguments : ['doctrine.orm.entity_manager']
        calls:
            - [ setTimezone, ['%welp_ical.default_timezone%']]
            - [ setProdid, ['%welp_ical.default_prodid%']]
